baseURL = "https://barrakuda.de/"
languageCode = "de-de"
title = "Stamm Barrakuda"
theme = "hugo-barrakuda-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id = ""
  subfooter = true
  repo = "github.com/stamm-barrakuda"

  [params.logo]
    mobile = "images/logo.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo-desktop.svg"
    desktop_height = "40px"
    desktop_width = "40px"
    alt = "Stamm Barrakuda"

  [params.homepage_meta_tags]
    meta_description = "Stamm Barrakuda - Bester Stamm der Welt"
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://barrakuda.de"
    # meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Stamm Barrakuda - Bester Stamm der Welt"

[[menu.main]]
    name = "Gruppen"
    url = "/gruppen/"
    weight = 1

[[menu.main]]
    name = "Lager"
    url = "/lager/"
    weight = 2

[[menu.main]]
    name = "Stamm"
    url = "/stamm/"
    weight = 3

[[menu.main]]
    name = "Stammesheim"
    url = "/stammesheim/"
    weight = 4

[[menu.main]]
    name = "Jubil√§um"
    url = "/jubilaeum/"
    weight = 5


[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
